### ISSUE TITLE
Download Particl Desktop Overlapping Over Everything

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#42] opened 2018-03-06 20:51 UTC
On Firefox ESR (Debian Stretch), the **Download Particl Desktop** green link in the header overlaps over everything. Not sure if resolution-specific, my monitor is 1400p. 

![selection_012](https://user-images.githubusercontent.com/27031337/37057630-000f477a-2156-11e8-84af-e1b321b4db10.png)
![selection_013](https://user-images.githubusercontent.com/27031337/37057631-002495b2-2156-11e8-9b0f-47ed849dc51d.png)
![selection_014](https://user-images.githubusercontent.com/27031337/37057632-0033f5fc-2156-11e8-83cd-62469225c55b.png)

**Comment by AllienWorks** [comment] 2018-03-07 14:26
@pciavald has the same issue, but I can't reproduce this. I will come back to this later and try to figure it out.

**Comment by AllienWorks** [comment] 2018-05-10 14:38
@cryptoguard this should be fixed now – can you confirm?

**Closed** 2018-05-10 14:38 UTC
Labels: bug
